name: jaguar_query_example
description: Dialect neutral, fluent Dart DSL to build SQL/NoSQL queries
version: 2.2.9
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: https://github.com/Jaguar-dart/jaguar_orm
documentation:

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  jaguar_query:
    git:
      url: "git://github.com/HTMHell/jaguar_orm.git"
      ref: "legacyV3"
      path: "query"

dev_dependencies:
  jaguar_query_postgres:
    git:
      url: "git://github.com/HTMHell/jaguar_orm.git"
      ref: "legacyV3"
      path: "postgres"