name: jaguar_orm_example
description: Source-generated ORM with relations (one-to-one, one-to-many, many-to-many), preloading, cascading, polymorphic relations, etc
version: 2.2.6
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
homepage: https://github.com/Jaguar-dart/jaguar_orm
documentation:

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  jaguar_orm:
    git:
      url: "git://github.com/HTMHell/jaguar_orm.git"
      ref: "legacyV3"
      path: "orm"
  jaguar_query_postgres:
    git:
      url: "git://github.com/HTMHell/jaguar_orm.git"
      ref: "legacyV3"
      path: "postgres"

dev_dependencies:
  build_runner:
  jaguar_orm_gen:
    git:
      url: "git://github.com/HTMHell/jaguar_orm.git"
      ref: "legacyV3"
      path: "generator"